# Generated by Django 2.0.5 on 2018-08-09 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('import_poc', models.TextField()),
                ('pluginID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30)),
                ('fqdn', models.CharField(max_length=255)),
                ('mac', models.CharField(max_length=30)),
                ('os', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProofOfConcept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poc', models.TextField()),
                ('tool', models.TextField()),
                ('finding', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Finding')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('port', models.IntegerField()),
                ('protocol', models.CharField(max_length=10)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='api.Host')),
            ],
        ),
        migrations.AddField(
            model_name='proofofconcept',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Service'),
        ),
        migrations.AddField(
            model_name='finding',
            name='services',
            field=models.ManyToManyField(through='api.ProofOfConcept', to='api.Service'),
        ),
    ]
