# Generated by Django 2.0.5 on 2018-08-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_proofofconcept_haspoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proofofconcept',
            name='haspoc',
            field=models.IntegerField(default=0),
        ),
    ]
