# Generated by Django 2.0.5 on 2018-08-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180809_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proofofconcept',
            name='poc',
            field=models.TextField(null=True),
        ),
    ]
