# Generated by Django 2.0.5 on 2018-08-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_proofofconcept_falsepositive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('executionstring', models.CharField(max_length=255)),
                ('expected_good', models.TextField()),
                ('expected_bad', models.TextField()),
            ],
        ),
    ]
