# Generated by Django 2.0.5 on 2018-08-17 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180813_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proofofconcept',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Service'),
        ),
    ]
